services:
  paku-backend:
    build:
      context: .
    container_name: paku-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - paku-net

networks:
  paku-net:
    external: true