services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: paku
      POSTGRES_USER: paku
      POSTGRES_PASSWORD: paku
    ports:
      - "5432:5432"
    volumes:
      - paku_pg:/var/lib/postgresql/data
volumes:
  paku_pg:
